### ISSUE TITLE
Translate to nginx without x11mirror-server (Возможность работы с nginx без x11mirror-server)

### ISSUE THREAD

**Issue by sosed213** [gh0stwizard/x11mirror-client#2]
Добрый день!
Возможно ли запустить x11mirror-client, и транслировать поток в nginx, без использования x11mirror-server?
Nginx и x11mirror-client работают в одной ОС.
Спасибо!

Good afternoon!
Is it possible to run x11mirror-client and stream to nginx without using x11mirror-server?
Nginx and x11mirror-client run on the same OS.
Thank you!

**Comment by gh0stwizard** [comment]
Hi there,
Sure, you may do this. The reason of creating separated server to convert X11 image format (X PixMap aka XPM) to png, jpg, etc. So, to exclude the server you may:
1) run nginx with Lua + ImageMagick + a bit of lua coding to convert XPM to jpg
2) write a custom convertor from XPM to jpg on client side (ImageMagick is huge, so see libXpm + NetPBM)
3) link ImageMagick with the client, it is easy but leads to track all dependencies of ImageMagick

**Comment by sosed213** [comment]
Спасибо большое за ответ.
Да, добавить возможность конвертирования из XPM в jpg, прям внутри клиента (x11mirror-client) было бы здорово.
И запускать клиента, например, с опцией x11mirror-client -o jpg (-o - output)
Но, к сожалению, моих знаний в программировании не достаточно, чтобы сделать такую доработку.


Thank you very much for the answer.
Yes, adding the ability to convert from XPM to jpg directly inside the client (x11mirror-client) would be great.
And run the client, for example, with the option x11mirror-client -o jpg
But, unfortunately, my knowledge in programming is not enough to make such a revision.

**Comment by gh0stwizard** [comment]
Done. Added new options:
*  `-O, --once` - create screenshot only once
* `-o -` - use **stdout** instead of saving to a file
* `-f <format>` - output format: png or jpg

For instance:
```
# export to Postscript
% ./x11mirror-client -O -o - -f jpg | jpegtopnm | pnmtops > /tmp/x11mirror.ps
```
Note that `jpegtopnm` & `pnmtops` are tools provided by [netpbm](https://netpbm.sourceforge.net/).

Added the example configuration for nginx, see [misc/nginx](https://github.com/gh0stwizard/x11mirror-client/tree/master/misc/nginx) for details.

Dependencies to build:
* PNG support via [libpng](http://www.libpng.org/)
`make WITH_PNG=YES|NO`
* JPG support via [libjpeg-turbo](https://libjpeg-turbo.org/)
`make WITH_JPG=YES|NO`

`XWD` support has been removed. Perhaps, it will be restored back later.
